Repository tzuhanchang/MadLAD, pull requests merged in 2024-04, with the labels that each got.

#36 Add `Processes` documentation
  docs/source/advanced/htcondor.md
  docs/source/processes/available_processes.md
  docs/source/tutorials/generate_events.md
  mkdocs.yml
Labels: documentation

#38 Fix error occurred when `docker` and `singularity` both exist
  madlad/build.py
  madlad/container/_check.py
  madlad/controls/exec.py
  madlad/controls/launch.py
  madlad/controls/post.py
Labels: bug, Priority

#39 Fix a bug introduced in #34
  madlad/controls/launch.py
Labels: bug, Priority

#40 Fix missing Singularity `%post` command indentation
  madlad/container/build.py
Labels: bug, Priority

#47 Fix `.sif` image finding bug, reopen #43
  madlad/container/_check.py
Labels: bug

#45 Change `no-shower` to `shower`
  madlad/controls/launch.py
  processes/4top.yaml
  processes/ttbar-allhad.yaml
Labels: Priority

#49 Add automatic Delphes execution
  madlad/controls/__init__.py
  madlad/controls/cleanup.py
  madlad/controls/delphes.py
  madlad/controls/launch.py
  processes/4top.yaml
  processes/ttbar-allhad.yaml
Labels: enhancement, Priority
